---
title: "2025-08-04 Java Spring GDS"
date: 2025-08-04
draft: false
---

= Tim Stephenson 
077988 67607 | tim@knowprocess.com 

== Summary  

* An experienced software engineer focussed on business goals through automation and digital transformation.
* A consultative developer well-versed with multiple languages including Java, Python, and TypeScript delivered in a cloud-native environment.
* Experienced running projects from small and scaling start-ups to high profile clients including UK government and NHS.  

## Education

2:1 Master of Engineering (Hons) from University of Manchester, 1997

== Professional Experience

=== March 2022 – Present: Elsevier

* Design, implement, maintain new application delivering insights on securing and optimising cost and reliability of cloud applications.
* Designed RESTful APIs and integrated them into frontend apps.
* SRE: Advising on migrating legacy Java backend services into cloud hosting, improving scalability and maintainability and implementing observability tooling.
* DevOps: Responsibility for implementing CI/CD pipelines initially with Jenkins then migration to and maintaince on GitHub Actions.

*Technologies*: Java 8,11,17, Spring Boot 2 & 3, Python, FastAPI, AWS Lambda, API Gateway, DynamoDB, Kubernetes, Docker, GitHub Actions, Terraform, OpenAPI (Swagger), NewRelic

=== Feb 2013 - 2022: KnowProcess (Freelance) 

Business automation and digital transformation consulting. 
Implementation of Business Process orchestration of Domain Driven and Decision Management based backend services. 

Highlighted projects below:

==== 2019-2021 Several Government departments 

* Defining software services to the Government Digital Service (GDS)’s Design Standard for user experience.
* Full stack development with Agile practices. Java microservices with web frontends.
* Security cleared.

*Technologies:* Java 8 & 11, Spring Boot 2 (backend REST APIs and frontends in Thymeleaf and Angular), Micro-services, TypeScript, Rest APIs, Keycloak, OAuth, OpenID, Postgres, BPMN, Docker, Kubernetes, AWS, OpenShift, Terraform, Helm

==== 2015-2022 Sustainable Reporting Portal for NHS

* Directed the development of innovative software products focused on non-financial (ESG) reporting and carbon calculations. 
* Spearheaded initiatives for supply chain traceability, enhancing transparency and sustainability. 
* Delivered a robust automation framework based on UK government research and data capable of generating accurate Carbon reports _'at the click of a button'_.
* Used by all NHS Trusts and Commissioners in England.
* Transitioned domain-driven monolith to cloud-based microservices. 

*Technologies:* Java 8 & 11, Spring MVC, Spring Security, Spring Boot, JavaScript, JPA, Liquibase, JWT, Keycloak, 
Postgres, Reactive web app, d3.js, Linux, DMN, Docker, Kubernetes, Terraform, Helm 

==== 2014-present Omny Link CRM and Workflow 

* SaaS offering to SMEs 
* Software as a Service offering lightweight CRM and workflow 

*Technologies:* Java, Spring MVC, Spring Security, Spring Boot, JPA, Liquibase, JWT, Keycloak, MySQL, Angular, Linux, BPMN, Docker, Kubernetes, Terraform, Helm 

==== 2013-2016 Climate KIC (start-up incubator at Imperial College) 

* A software start-up for tracking and managing down carbon emissions. Ultimately transitioned to the NHS project work above. 
* Gained valuable experience on Business Model Canvas, Lean Start-up, and start-up environments.

*Technologies:* Java, Docker, Kubernetes, Spring MVC, Spring Security, Spring Boot, JPA, Liquibase, JWT, Postgres, Reactive web app, d3.js, Linux

==== 2014-2016 Discover North Somerset: http://discovernorthsomerset.co.uk/ 

* Showcased the wealth of local businesses and attractions in North Somerset, providing a platform for local tourism and commerce.
* Integrated existing council Open Data.
 
*Technologies:* WordPress, Python, Open Data server (CKAN and Redbridge) 

=== Feb 2012 - Jan 2013: Technical Architect, Helveta  

* A funded start-up, I reported to board and was responsible for design and delivery of next generation sustainable Supply tracking product for timber industry.  
* Initiated new product development team (offshore) and establishment of agile development practices.  
* Mentoring to team leads on technology issues including hands-on and whiteboard activities and everything in between.  

=== Dec 2010 - Feb 2012: Technical founder, pailz.com  

* Team management solution 
* Front end in Python (Django), backend in Java, hosted on Google App Engine
* Editor on Workflow Management Coalition (WfMC)'s Business Process Simulation standard. 

=== Jan 2004 - Nov 2010: Engineering Director, TIBCO Software Inc. (previously Staffware), UK  

* Reported to VP of Business Process Management engineering team with frequent interaction with other engineering and marketing managers at SVP, VP and Director level.  
* Driving force behind the award winning TIBCO Business Studio modelling environment from conception to v3, which, to quote a customer is “revolutionising what we can achieve with BPM”  
* Regularly asked to speak to internal and customer audiences (2-200 people) on the BPM vision and how Studio facilitates it.  
* Championed an Agile development culture of shared responsibility and continuous process improvement and test-driven development.  
* Lead the team through the transitional period, mentoring each individual, especially the promotion of two into team leaders as the team grew.  
* Product visions and roadmaps, requirements specifications, user guides and training materials.  
* Responsible for all aspects of delivery of the vision for a BPM-SOA enabled solution for the Insurance market with the goal of an order of magnitude increase in deal size.  
* Hired and formed a new delivery team to build out the solution.

=== Jun 2003 - Dec 2003: Consultant at Hummingbird, UK  

=== Oct 2001 - Mar 2003: Technical Specialist with Technology One, Australia 

=== Oct 1998 - July 2001: Principal Consultant with Sybase Professional Services, UK  

=== Aug 1997 - Oct 1998: Analyst / Developer with Admiral Computing, now LogicaCMG 
