---
title: "2025 06 18 Stephenson"
date: 2025-06-18
draft: false
---

= Tim Stephenson 
077988 67607 | tim@knowprocess.com 

== Summary  

* An experienced software engineer focused on business goals through automation and digital transformation.
* A consultative individual contributor, with leadership experience, well-versed with multiple languages including Python, Java, and TypeScript delivered in a cloud-native environment.
* I'm self-starting, used to remote working but value face time too.
* Looking for contract work but open to the right permanent role
* Security cleared (SC).

## Education

2:1 Master of Engineering (Hons) from University of Manchester, 1997

== Professional Experience

=== March 2022 – Present: Senior Site Reliability Engineer, Elsevier

* Design, implement, maintain new application delivering insights on securing and optimising cost and reliability of cloud applications.
* Designed RESTful APIs and integrated them into frontend apps.
* SRE: Advising on migrating legacy backend services into cloud hosting, improving scalability and maintainability through both code review and observability tooling.
* DevOps: Responsibility for implementing CI/CD pipelines initially with Jenkins then migration to and maintaince on GitHub Actions.

*Technologies*: Python, FastAPI, AWS Lambda, API Gateway, DynamoDB, Kubernetes, Docker, GitHub Actions, Terraform, OpenAPI (Swagger), NewRelic

=== Jan 2019 - Dec 2021: Solutions Architect, Zaizi - on behalf of several UK Govenment departments

* Defining software services to the Government Digital Service (GDS)'s Design Standard for user experience.
* Full stack development with Agile practices. Java and Python with TypeScript front end.
* Security cleared (SC).

*Technologies:* Python 3, Robot Framework, Java 8 & 11, Spring Boot, Micro-services, TypeScript, Rest APIs, Keycloak, OAuth, OpenID, Angular, Postgres, BPMN, Docker, Kubernetes, AWS, OpenShift, Terraform, Helm 

=== Mar 2015 - Dec 2018: Lead Software Engineer, KnowProcess - on behalf of NHS England

* Development of innovative software products focused on non-financial (ESG) reporting and carbon calculations.
* Spearheaded initiatives for supply chain traceability, enhancing transparency and sustainability.
* Delivered a robust automation framework based on UK government research and data capable of generating accurate Carbon reports _'at the click of a button'_.
* Used by all NHS Trusts and Commissioners in England.
* Domain-driven microservices on public cloud hosting.

*Technologies:* Java 8 & 11, Spring MVC, Spring Security, Spring Boot, JavaScript, JPA, Liquibase, JWT, Keycloak, Postgres, Reactive web app, d3.js, Linux, DMN, Docker, Kubernetes, Terraform, Helm

=== Feb 2013 - Feb 2015: Technical Founder, Trakeo - incubalted at Imperial College, London

* A software start-up for tracking and managing down carbon emissions. Ultimately transitioned to the NHS project work above.
* Gained valuable experience on Business Model Canvas, Lean Start-up, and start-up environments.

*Technologies:* Java, Docker, Spring MVC, Spring Security, Spring Boot, JPA, Liquibase, JWT, Postgres, Reactive web app, d3.js, Linux

=== Feb 2011 - Feb 2013: Technical Architect, Helveta

* A funded start-up, I reported to board and was responsible for design and delivery of next generation sustainable Supply tracking product for timber industry.
* Initiated new product development team (offshore) and establishment of agile development practices.
* Mentoring to team leads on technology issues including hands-on and whiteboard activities and everything in between.

=== Jan 2004 - Dec 2010: Engineering Director, TIBCO

* Reported to VP of Business Process Management engineering team with frequent interaction with other engineering and marketing managers at SVP, VP and Director level.
* Driving force behind the award winning TIBCO Business Studio modelling environment from conception to v3, which, to quote a customer is "revolutionising what we can achieve with BPM"
* Regularly asked to speak to internal and customer audiences (2-200 people) on the BPM vision and how Studio facilitates it.
* Product visions and roadmaps, requirements specifications, user guides and training materials.
* Hired and lead a development team for multiple years and transitions, I am particularly proud of mentoring each individual, especially the promotion of two into team leaders as the team grew.

=== Jun 2003 - Dec 2003: Consultant at Hummingbird, UK  

=== Oct 2001 - Mar 2003: Technical Specialist with Technology One, Australia 

=== Oct 1998 - July 2001: Principal Consultant with Sybase Professional Services, UK  

=== Aug 1997 - Oct 1998: Analyst / Developer with Admiral Computing, now LogicaCMG 
